title: Metanorma
description: The standard of standards
# The above two are used by jekyll-seo-tag for things such as
# `<title>` and `<meta>` tags, as well as elsewhere by the theme.

permalink: /blog/:year-:month-:day-:title/

algolia_search:
  api_key: '31ca4bad475130bdaee582a0b9f40806'
  index_name: 'metanorma'

landing_priority: [custom_intro, blog, specs, software]

tagline: >-
  Because standards&nbsp;are too&nbsp;important to&nbsp;manage in&nbsp;Word

author: "Ribose Inc."

authors:
  - name: Ribose Inc.
    email: open.source@ribose.com

contact_email: open.source@ribose.com

theme: jekyll-theme-open-project

parent_hub:
  git_repo_url: https://github.com/riboseinc/open.ribose.com
  home_url: https://open.ribose.com/

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/riboseinc/metanorma

legal:
  name: Ribose Group Inc.
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

home_calls_to_action:
  - { url: "/author/getting-started/", title: "Get Started" }

collections:
  samples:
    output: true
    permalink: /samples/:path/

defaults:
  - scope:
      path: _samples
      type: samples
    values:
      layout: spec-sample

  # Theme defaults.
  # MUST be duplicated from theme’s _config.yml
  # (does not get inherited, unlike the collections hash)
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  - scope:
      path: _software
      type: software
    values:
      layout: product
  - scope:
      path: _specs
      type: specs
    values:
      layout: spec

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

url: https://www.metanorma.com

github_repo_url: https://github.com/metanorma/metanorma.com

tag_namespaces:
  software:
    writtenin: "Written in"
    bindingsfor: "Bindings for"
    user: "Target user"
    interface: "Interface"
  specs:
    audience: "Audience"
    completion_status: "Status"

exclude:
  - Gemfile*
  - Makefile
  - Rakefile
  - README.adoc
  - vendor # for deployment
